### ISSUE TITLE
Please update NPM package

### ISSUE THREAD

**Issue by kib357** [xyc/react-object-inspector#13]

**Comment by vickychijwani** [comment]
+1. Please update this package. ~~React v0.14 [was released a week ago](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html).~~ (EDIT: just saw #11, which means only an `npm publish` is needed).

**Comment by xyc** [comment]
Will update soon. Thanks.

**Comment by xyc** [comment]
Will also include the changes from React v0.14. Please stay tuned.

**Comment by ForbesLindesay** [comment]
Is there anything else that needs doing before publishing?  Anything I can help with?

**Comment by xyc** [comment]
not too much needs to be done actually... Just been too busy recently. I have added some tests and working on the default configs, maybe I'll just stash the changes and publish it first. please ping me if you haven't heard back early next week

**Comment by xyc** [comment]
And thanks for your help @ForbesLindesay . For 0.14 probably need to add react-dom to this. If you have suggestions about best practices for inline styles, please let me know.

**Comment by xyc** [comment]
NPM package updated to 0.1.6.
