### ISSUE TITLE
Support inspection of __proto__ for function

### ISSUE THREAD

**Issue by abhishiv** [xyc/react-object-inspector#18]
Hey xyc

Really great work! 

I just wanted to know what you think about adding support for inspection of proprties like `__proto__`, just the way it does in chrome dev tools?

**Comment by xyc** [comment]
I'm considering it :)

**Comment by xyc** [comment]
Hi Abhishiv, 

I'm working on the 1.0.0 version of this project which has easier APIs.
Would you mind sharing some use cases where you needed `__proto__?` This will help with prioritizing. Thanks so much.

**Comment by abhishiv** [comment]
Hey Xiaoyi

Thanks! My use case is actually quite specific. I'm actually trying to build an IDE in the browser - you can check it out here - https://www.grati.co/_admin. I compile javascript source via System module loader, and then use react-object-inspector to visualize the module object. __proto would help here for debugging purpose.

Btw, I also found this which might help - facebook/react-devtools#293

**Comment by xyc** [comment]
Cool project! Thanks very much for the link, I'll look into it

**Comment by xyc** [comment]
Please try the latest version of react-inspector and use `showNonenumerable`
