### ISSUE TITLE
Unknown Babel option: stage

### ISSUE THREAD

**Issue by unformatt** [xyc/react-object-inspector#20]
Babel 6.5.2

```
Module build failed: ReferenceError: [BABEL] ...node_modules/react-object-inspector/lib/ObjectInspector.js: Unknown option: ...node_modules/react-object-inspector/.babelrc.stage
```

react-object-inspector/.babelrc

```
{
  "stage": 0
}
```

**Comment by xyc** [comment]
When did you get this error? In the building stage?

**Comment by unformatt** [comment]
Yes, my guess is `babel-preset-stage-0` is needed in the dependencies.

**Comment by xyc** [comment]
I think this project doesn't use stage-0 features. I will remove the option.

**Comment by xyc** [comment]
Preparing to upgrade to Babel 6 and an overhaul of this project. Please stay tuned.
