### ISSUE TITLE
Arrow character mangled by babel?

### ISSUE THREAD

**Issue by TomKaltz** [xyc/react-object-inspector#22]
I am using babel and for some reason the arrow character isn't rendering correctly...
![screen shot 2016-10-04 at 11 19 24 am](https://cloud.githubusercontent.com/assets/2965281/19080266/8bf99724-8a24-11e6-8e27-af4c4484beb5.png)

Could it be babel?

**Comment by xyc** [comment]
Would adding `<meta charset="UTF-8">` work?

**Comment by TomKaltz** [comment]
Yes, indeed that worked!
