### ISSUE TITLE
Feature request: collapsed / expanded state / root node

### ISSUE THREAD

**Issue by austinnichols101** [xyc/react-object-inspector#5]
I would like to be able to specify the collapsed / expanded state of the component:

a) expand a specific path "object.foo.bar"

b) expand noes down to a specific level number - ex: level 1 expands "object.keys" and level 2 expands "object.keys.keys"

Would also be nice to be able to override the label for the root node.

**Comment by xyc** [comment]
Will consider adding an initial expanded/collapsed option props.
You can specify the 'name' prop to set the root node label

**Comment by xyc** [comment]
This issue is resolved in 0.2.0. See readme for more details.
