### ISSUE TITLE
"undefined" is rendered as Object

### ISSUE THREAD

**Issue by stomita** [xyc/react-object-inspector#6]
The undefined value is rendered as Object.

Attached shot is from [demo page](http://xyc.github.io/react-object-inspector/):

![sample app](https://cloud.githubusercontent.com/assets/23387/9400585/09d9e8e8-47fe-11e5-879f-b3f9017bc24f.jpg)

**Comment by xyc** [comment]
I set the default props for data to `{}`; React will use default props when passed in `undefined`. Will fix in next version by changing default props to `undefined`.

**Comment by xyc** [comment]
Resolved in 0.1.5
